name: aiao-env
channels:                  
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - keras
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - scikeras